branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: caleb1-dev
global:
  application_name: caleb1
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
